### ISSUE TITLE
希望调整布局，以适应不同分辨率的电脑

### ISSUE THREAD

**Issue by obscurefreeman** [zhangyu1818/appicon-forge#1]
如图，无法看清图标预览
![image](https://github.com/user-attachments/assets/555dabae-493c-4d39-9177-2a86e725a644)

**Comment by zhangyu1818** [comment]
已增加折叠功能，折叠后只显示输入框方便搜索，请清除缓存后重新访问

**Comment by obscurefreeman** [comment]
感谢大佬增加的折叠功能，可惜调整图表样式时不能看到图表全貌还是有点难受。
建议选项栏折叠后仍然能看到选项，并且增加滚动条以便查看所有选项。或者将选项栏移动至左侧。
![image](https://github.com/user-attachments/assets/60863f90-966f-4cef-8508-321070766ac4)
![image](https://github.com/user-attachments/assets/8d737775-3d92-479f-be3d-d80537294a7d)

**Comment by zhangyu1818** [comment]
增加了一个切换左右排列的按钮，你看看这样好些了没

**Comment by zhangyu1818** [comment]
因为重新开发了新版并新增了一些功能，所以关闭这个旧版的Issue。

**Comment by obscurefreeman** [comment]
效率惊人啊，老兄有把它制作成独立软件的打算吗？

**Comment by zhangyu1818** [comment]
没有这个打算哈，网页版是有一些功能实现不了，但是开发比较简单，套壳网页的软件和网页版没区别，跨平台GUI开发我又不会😂
