### ISSUE TITLE
希望增加只下载图标的功能

### ISSUE THREAD

**Issue by Tanuyoki** [zhangyu1818/appicon-forge#14]
有时候只想下载图标，不想要带背景的，比如图片上这种
![image](https://github.com/user-attachments/assets/adbac112-f7bd-459a-a460-e9ea698bd8c5)

**Comment by zhangyu1818** [comment]
可以把背景和边框颜色都设置成透明，如果只下图标，建议去[iconify](https://icon-sets.iconify.design/)下载
