### ISSUE TITLE
希望可以下载合成后的svg格式样式

### ISSUE THREAD

**Issue by YsLtr** [zhangyu1818/appicon-forge#23]
现在的图标下载只支持下载png，虽然可以调整分辨率，但是做前端的时候使用svg的频率还是更多。
比如下面这个网站，都是下载svg格式的图标。麻烦作者大大了。🫡

https://www.xicons.org/#/

**Comment by zhangyu1818** [comment]
SVG图标可以直接去[iconify](https://icon-sets.iconify.design/)下载，这个项目初衷是在不会设计图标的情况下创建一个简易的APP图标。

目前的实现如果生成SVG，也是用的SVG的image标签，不是矢量图。
