### ISSUE TITLE
希望能设置输出分辨率

### ISSUE THREAD

**Issue by Feliks151450** [zhangyu1818/appicon-forge#3]
目前图标的分辨率和网页缩放比例有关系，我mbp上测试缩到最小的时候是528x528，常用的缩放下是1900x1900。
对于一些图标只需要50x50这种大小的来说，没法直接输出这类图标

**Comment by zhangyu1818** [comment]
我调整了一下，增加了一个输入框，可以设置图片的分辨率，同时修复了物理分辨率比例的问题，但是如果是网页缩放没办法控制。

但调太高或太低分辨率可能会导致阴影效果太锐利，建议生成默认的1024分辨率，再通过工具去生成各种平台大小的图标，如果是简单的图片缩小，可以用imagemagick转一下。

**Comment by zhangyu1818** [comment]
因为重新开发了新版并新增了一些功能，所以关闭这个旧版的Issue。
